# langchain FAISS
> **Facebook AI Similarity Search**

## synchronous 


**[ASYNC版本](https://python.langchain.com/docs/integrations/vectorstores/async_faiss)**

In [19]:
from langchain.embeddings.openai import OpenAIEmbeddings
from langchain.text_splitter import CharacterTextSplitter
from langchain.vectorstores import FAISS
from langchain.document_loaders import TextLoader

In [20]:
from langchain.document_loaders import TextLoader

In [21]:
loader = TextLoader('./input/state_of_chinese.txt')

In [22]:
documents = loader.load()

In [23]:
documents.__len__()

1

In [30]:
# text_splitter = CharacterTextSplitter(chunk_size=1000, chunk_overlap=0)
text_splitter = CharacterTextSplitter(chunk_size=0, chunk_overlap=0) # 这样就是按照段落分

In [31]:
docs = text_splitter.split_documents(documents)

Created a chunk of size 67, which is longer than the specified 0
Created a chunk of size 121, which is longer than the specified 0
Created a chunk of size 109, which is longer than the specified 0
Created a chunk of size 156, which is longer than the specified 0
Created a chunk of size 140, which is longer than the specified 0
Created a chunk of size 24, which is longer than the specified 0
Created a chunk of size 93, which is longer than the specified 0
Created a chunk of size 136, which is longer than the specified 0
Created a chunk of size 32, which is longer than the specified 0
Created a chunk of size 150, which is longer than the specified 0
Created a chunk of size 24, which is longer than the specified 0
Created a chunk of size 255, which is longer than the specified 0
Created a chunk of size 132, which is longer than the specified 0
Created a chunk of size 56, which is longer than the specified 0
Created a chunk of size 40, which is longer than the specified 0
Created a chunk o

In [32]:
embeddings = OpenAIEmbeddings()

In [33]:
docs.__len__()

17

In [35]:
for doc in docs:
    print(doc.page_content)

“教育是一个国家的未来，是一个民族的希望。”我相信，每一位阅读这篇文章的人，无论是在校学生，家长，还是教育工作者，都深知教育的重要性。
然而，传统的教育模式面临着许多挑战：课堂内的教学模式单一，教师难以顾及每一位学生的个性化需求，学生的学习进度和成绩又受到诸多因素的影响。而这些问题，可能通过AIGC技术得到解决。AIGC，全称为人工智能生成内容，是现代AI技术的重要应用之一。
那么，AIGC技术在教育领域有哪些应用？AIGC技术在教育领域的优缺点又是什么呢？在教育领域，AI是否能替代人类教师的角色？？AIGC教育领域的应用可能带来哪些伦理问题呢？这些问题，我将在接下来的文章中为大家一一解答。
我们首先来看看AIGC技术在教育领域的应用。Quizlet联合OpenAI推出了名为Q-Chat的人工智能辅导工具，这个工具可以提供个性化的一对一辅导，通过聊天界面和针对性的问题，帮助学生学习各个学科。这不仅仅是一种新的学习方式，更是一种全新的学习体验。Q-Chat的出现，让我们看到了AI在教育领域的巨大潜力。
同样，在语言学习领域，Duolingo也引入了OpenAI的GPT-4，开发了AI对话伙伴和解释答案两个新功能，以提升学习者在学习第二语言时的效率和兴趣。另外，非营利组织Khan Academy宣布将使用GPT-4推出AI助手Khanmigo，作为学生的虚拟导师和教师的课堂助手。
那么，AIGC技术在教育领域应用有哪些优缺点呢？
优点显而易见，首先，AIGC技术可以实现个性化学习，提供定制化的教学内容，提升学习效率。其次，AI助手可以提供全天候服务，打破时间和地点的限制，让学习更为灵活，学生可以随时随地进行学习。
然而，任何事物的发展都有其两面性，缺点同样存在。例如，过度依赖AI可能会导致学生缺乏人际交流的机会，影响他们的社交能力。这不仅包括语言交流，还有面对面的情感交流、情绪理解和社会性行为。人类社会是一个复杂的系统，充满了微妙的情感和社会关系，这是AI暂时无法完全理解和模拟的。
面对这种情况，我们要思考，AIGC技术是否能替代人类教师的角色？
我认为，AIGC技术并不能完全替代人类教师。教师的角色不仅在于传递知识，他们的情感投入以及对学生个性和需求的理解是AI无法替代的。然而，AIGC技术可以成为教师的得力助手，比如，Khan Academy的AI助手Khanmig

In [36]:
db = FAISS.from_documents(docs, embeddings)

### 1. 字符串查

In [37]:
query = "AIGC技术是否能替代人类教师的角色"

In [38]:
docs = db.similarity_search(query)

In [39]:
docs.__len__()

4

In [41]:
for doc in docs:
    print(doc.page_content)

面对这种情况，我们要思考，AIGC技术是否能替代人类教师的角色？
我认为，AIGC技术并不能完全替代人类教师。教师的角色不仅在于传递知识，他们的情感投入以及对学生个性和需求的理解是AI无法替代的。然而，AIGC技术可以成为教师的得力助手，比如，Khan Academy的AI助手Khanmigo，能够帮助教师编写课堂提示或创建教学材料，更好地满足每个学生的学习需求。
那么，AIGC技术在教育领域有哪些应用？AIGC技术在教育领域的优缺点又是什么呢？在教育领域，AI是否能替代人类教师的角色？？AIGC教育领域的应用可能带来哪些伦理问题呢？这些问题，我将在接下来的文章中为大家一一解答。
那么，AIGC技术在教育领域应用有哪些优缺点呢？


### 2. 字符串查,且返回分数

`similarity_search_with_score`
1. L2 distance : a lower score is better
2. 不仅返回文档,还返回score

In [42]:
docs_and_scores = db.similarity_search_with_score(query)

In [44]:
for doc, score in docs_and_scores:
    print(doc.page_content, score)

面对这种情况，我们要思考，AIGC技术是否能替代人类教师的角色？ 0.08710252
我认为，AIGC技术并不能完全替代人类教师。教师的角色不仅在于传递知识，他们的情感投入以及对学生个性和需求的理解是AI无法替代的。然而，AIGC技术可以成为教师的得力助手，比如，Khan Academy的AI助手Khanmigo，能够帮助教师编写课堂提示或创建教学材料，更好地满足每个学生的学习需求。 0.14040501
那么，AIGC技术在教育领域有哪些应用？AIGC技术在教育领域的优缺点又是什么呢？在教育领域，AI是否能替代人类教师的角色？？AIGC教育领域的应用可能带来哪些伦理问题呢？这些问题，我将在接下来的文章中为大家一一解答。 0.183281
那么，AIGC技术在教育领域应用有哪些优缺点呢？ 0.20547959


>  欧式距离, 越小越相似

### 3. 根据向量查

In [45]:
embedding_vector = embeddings.embed_query(query)

In [46]:
for doc, score in db.similarity_search_with_score_by_vector(embedding_vector):
    print(doc.page_content, score)

面对这种情况，我们要思考，AIGC技术是否能替代人类教师的角色？ 0.0871196
我认为，AIGC技术并不能完全替代人类教师。教师的角色不仅在于传递知识，他们的情感投入以及对学生个性和需求的理解是AI无法替代的。然而，AIGC技术可以成为教师的得力助手，比如，Khan Academy的AI助手Khanmigo，能够帮助教师编写课堂提示或创建教学材料，更好地满足每个学生的学习需求。 0.1403518
那么，AIGC技术在教育领域有哪些应用？AIGC技术在教育领域的优缺点又是什么呢？在教育领域，AI是否能替代人类教师的角色？？AIGC教育领域的应用可能带来哪些伦理问题呢？这些问题，我将在接下来的文章中为大家一一解答。 0.18336548
那么，AIGC技术在教育领域应用有哪些优缺点呢？ 0.20562895


### 4. Saving and loading

In [21]:
db.save_local('./faiss_index')

In [22]:
new_db = FAISS.load_local('./faiss_index', embeddings)

### 5. Serializing and De-Serializing to bytes

1. save_local 空间很大, 
2. 序列化接口很小, 如果要将向量库持久化到sql数据库, 这是个不错的选择. 

In [ ]:
from langchain.embeddings.huggingface import HuggingFaceEmbeddings

**序列化**

In [23]:
pkl = db.serialize_to_bytes()

**反序列化**

In [24]:
db = FAISS.deserialize_from_bytes(embeddings=embeddings, serialized=pkl)

### 6. Merging, 合并索引

In [25]:
db1 = FAISS.from_texts(["foo"], embeddings)
db2 = FAISS.from_texts(['bar'], embeddings)

In [26]:
db1.docstore._dict

{'1c3c6c3d-d931-44dc-b147-96cddd259275': Document(page_content='foo')}

In [27]:
db2.docstore._dict

{'3d91c136-36bf-462a-9248-14adec957622': Document(page_content='bar')}

In [28]:
db1.merge_from(db2)

In [29]:
db1.docstore._dict

{'1c3c6c3d-d931-44dc-b147-96cddd259275': Document(page_content='foo'),
 '3d91c136-36bf-462a-9248-14adec957622': Document(page_content='bar')}

### 7. 带过滤器的相似度查找

> 1. fetch_k : 是过滤之前获取的文档数 <br>

In [30]:
from langchain.schema import Document

In [31]:
list_of_documents = [
    Document(page_content="foo", metadata=dict(page=1)),
    Document(page_content="bar", metadata=dict(page=1)),
    Document(page_content="foo", metadata=dict(page=2)),
    Document(page_content="barbar", metadata=dict(page=2)),
    Document(page_content="foo", metadata=dict(page=3)),
    Document(page_content="bar burr", metadata=dict(page=3)),
    Document(page_content="foo", metadata=dict(page=4)),
    Document(page_content="bar bruh", metadata=dict(page=4)),
]

In [52]:
db = FAISS.from_documents(list_of_documents, embeddings)

In [33]:
results_with_scores = db.similarity_search_with_score("foo")

In [34]:
for doc, score in results_with_scores:
    print(f"Content: {doc.page_content}, Metadata: {doc.metadata}, Score: {score}")

Content: foo, Metadata: {'page': 1}, Score: 0.0
Content: foo, Metadata: {'page': 2}, Score: 0.0
Content: foo, Metadata: {'page': 3}, Score: 0.0
Content: foo, Metadata: {'page': 4}, Score: 0.0


> Now we make the same query call but we filter for only `page = 1`

In [35]:
results_with_scores = db.similarity_search_with_score("foo", filter=dict(page=1))
for doc, score in results_with_scores:
    print(f"Content: {doc.page_content}, Metadata: {doc.metadata}, Score: {score}")

Content: foo, Metadata: {'page': 1}, Score: 1.4206954801920801e-05
Content: bar, Metadata: {'page': 1}, Score: 0.3131061792373657


> Same thing can be done with the `max_marginal_relevance_search` as well.

In [36]:
results = db.max_marginal_relevance_search("foo", filter=dict(page=1))
for doc in results:
    print(f"Content: {doc.page_content}, Metadata: {doc.metadata}")

Content: foo, Metadata: {'page': 1}
Content: bar, Metadata: {'page': 1}


> `fetch_k` parameter is the number of documents that will be fetched before filtering<br>
> `fetch_k` parameter 是在过滤之前抓取的文档数量

In [37]:
results = db.similarity_search("foo", filter=dict(page=1), k=1, fetch_k=4)
for doc in results:
    print(f"Content: {doc.page_content}, Metadata: {doc.metadata}")

Content: foo, Metadata: {'page': 1}


In [53]:
db.index_to_docstore_id

{0: 'a992967c-761b-4fe6-9f64-5aa7ed88d545',
 1: 'ba1094b9-b7c8-437c-a1db-33c1a39fdfe1',
 2: 'b31d8eac-3d9c-4d26-8244-2272a14b9122',
 3: 'a8dc35f4-6334-42ae-b76d-87fb5a123674',
 4: '7a95ca75-8b31-4744-8a7b-f41915b09c6e',
 5: 'a3f06aaf-096b-48fe-ba16-36a3da942f65',
 6: '9aa83411-5832-41c1-8fff-091e13f2cd5e',
 7: '3d8263fd-7c18-444c-b5e4-b3d73b5abf91'}

In [54]:
db.index_to_docstore_id[0]

'a992967c-761b-4fe6-9f64-5aa7ed88d545'

In [55]:
db.delete([db.index_to_docstore_id[0]])

True

In [56]:
0 in db.index_to_docstore_id

True

In [57]:
db.index_to_docstore_id

{0: 'ba1094b9-b7c8-437c-a1db-33c1a39fdfe1',
 1: 'b31d8eac-3d9c-4d26-8244-2272a14b9122',
 2: 'a8dc35f4-6334-42ae-b76d-87fb5a123674',
 3: '7a95ca75-8b31-4744-8a7b-f41915b09c6e',
 4: 'a3f06aaf-096b-48fe-ba16-36a3da942f65',
 5: '9aa83411-5832-41c1-8fff-091e13f2cd5e',
 6: '3d8263fd-7c18-444c-b5e4-b3d73b5abf91'}

> 少了一个 `a992967c-761b-4fe6-9f64-5aa7ed88d545`

In [58]:
db.add_documents?

Signature: db.add_documents(documents: 'List[Document]', **kwargs: 'Any') -> 'List[str]'
Docstring:
Run more documents through the embeddings and add to the vectorstore.

Args:
    documents (List[Document]: Documents to add to the vectorstore.

Returns:
    List[str]: List of IDs of the added texts.
File:      /opt/conda/envs/preventloss/lib/python3.9/site-packages/langchain/schema/vectorstore.py
Type:      method

In [59]:
db.add_texts?

Signature:
db.add_texts(
    texts: 'Iterable[str]',
    metadatas: 'Optional[List[dict]]' = None,
    ids: 'Optional[List[str]]' = None,
    **kwargs: 'Any',
) -> 'List[str]'
Docstring:
Run more texts through the embeddings and add to the vectorstore.

Args:
    texts: Iterable of strings to add to the vectorstore.
    metadatas: Optional list of metadatas associated with the texts.
    ids: Optional list of unique IDs.

Returns:
    List of ids from adding the texts into the vectorstore.
File:      /opt/conda/envs/preventloss/lib/python3.9/site-packages/langchain/vectorstores/faiss.py
Type:      method

# facebook faiss

[wiki-get start](https://github.com/facebookresearch/faiss/wiki/Getting-started)

## Basic Info

> full name:  facebook ai similarity search<br>
> Faiss uses only 32-bit floating point matrics.<br>
> fixed dimensionality: $\rm \large d$<br>
> we need two matrics:<br>
>> * xb: index and search. size: $\rm \large nb \times d$<br>
>> * xq: query. size: $\rm \large nq \times d$, if we have a single query vector, $\rm \large nq = 1$<br>
>> * query result $\rm \large nq \times k$, 因为每个qeury返回k近邻


## basic usage


* 构建索引index
* 根据不同索引的特性，对索引进行训练（train）
* add 添加xb数据到索引
* 针对xq进行搜索search操作

### prepare data

folloing examples:<br>
1. $\rm \large d=64$ <br>
2. sampling from uniform distribution

In [1]:
import numpy as np

In [2]:
d = 64                # dimension
nb = 10000            # database size
nq = 1000             # queries size
np.random.seed(1234)  # make reproducible

xb = np.random.random((nb, d)).astype('float32')
xb[:, 0] += np.arange(nb) / 1000.
xq = np.random.random((nq, d)).astype('float32')
xq[:, 0] += np.arange(nq) / 1000.

### Building an index and adding the vectors to it


### training

> 这里不详细说了, 一堆索引类型

In [3]:
import faiss

In [4]:
index = faiss.IndexFlatL2(d)  # build the index

> IndexFlatL2不需要训练过程

In [16]:
index.is_trained    # IndexFlatL2不需要训练过程

True

In [6]:
index.add(xb)

In [7]:
index.ntotal

10000

### Searching

> The basic search operation that can be performed on an index is the k-nearest-neighbor search, ie. for each query vector, find its k nearest neighbors in the database.<br>
> 做 `k-nearest-neigbhor` 搜索, 针对每个query 返回 `k`个 最近邻.<br>


>> * xb: index and search. size: $\rm \large nb \times d$<br>
>> * xq: query. size: $\rm \large nq \times d$, if we have a single query vector, $\rm \large nq = 1$<br>
>> * query result $\rm \large nq \times k$, 因为每个qeury返回k近邻

In [13]:
index.search?

Signature: index.search(x, k, *, params=None, D=None, I=None)
Docstring:
Find the k nearest neighbors of the set of vectors x in the index.

Parameters
----------
x : array_like
    Query vectors, shape (n, d) where d is appropriate for the index.
    `dtype` must be float32.
k : int
    Number of nearest neighbors.
params : SearchParameters
    Search parameters of the current search (overrides the class-level params)
D : array_like, optional
    Distance array to store the result.
I : array_like, optional
    Labels array to store the results.

Returns
-------
D : array_like
    Distances of the nearest neighbors, shape (n, k). When not enough results are found
    the label is set to +Inf or -Inf.
I : array_like
    Labels of the nearest neighbors, shape (n, k).
    When not enough results are found, the label is set to -1
File:      /opt/conda/envs/preventloss/lib/python3.9/site-packages/faiss/class_wrappers.py
Type:      method

In [14]:
k = 4          # 4 nearest neighbors
D, I = index.search(xb[:5], k)  # sanity check 合法性检查
print(I)
print(D)
D, I = index.search(xq, k)
print(I[:5])
print(I[-5:])

[[  0 393 363  78]
 [  1 555 277 364]
 [  2 304 101  13]
 [  3 173  18 182]
 [  4 288 370 531]]
[[0.        7.1751738 7.20763   7.2511625]
 [0.        6.3235645 6.684581  6.799946 ]
 [0.        5.7964087 6.391736  7.2815123]
 [0.        7.2779055 7.5279875 7.662846 ]
 [0.        6.7638035 7.2951202 7.3688145]]
[[ 794   72  515 1204]
 [ 393  919  424  923]
 [ 688  806  763  185]
 [ 950  230  317  703]
 [ 199  409  411  794]]
[[1682 1663 1766 1759]
 [1225 1501 1193 1656]
 [1095 1369 1308  958]
 [1346 1386 1136  664]
 [ 627  308  678  856]]


* $\rm \large I$的维度是 $\rm \large nq \times 4$,代表距离每个query最近的k个数据的id
* $\rm \large D$的维度是 $\rm \large nq \times 4$,代表距离每个query最近的k个数据的距离

> * sanity check的输出:  与$\rm \large xb[:5]$最相似的都是自身, 索引 最相似的索引都是第一个 第4相似的是第4列. 同样的第二个矩阵的第一列都是零,因为 自身的欧式距离是 0